/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/关于代码规范的一些粗浅想法': RouteRecordInfo<
      '/posts/关于代码规范的一些粗浅想法',
      '/posts/%E5%85%B3%E4%BA%8E%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83%E7%9A%84%E4%B8%80%E4%BA%9B%E7%B2%97%E6%B5%85%E6%83%B3%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/分布式事务 Seata 学习笔记': RouteRecordInfo<
      '/posts/分布式事务 Seata 学习笔记',
      '/posts/%E5%88%86%E5%B8%83%E5%BC%8F%E4%BA%8B%E5%8A%A1%20Seata%20%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/北京、海、雨': RouteRecordInfo<
      '/posts/北京、海、雨',
      '/posts/%E5%8C%97%E4%BA%AC%E3%80%81%E6%B5%B7%E3%80%81%E9%9B%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/常用业务代码片段': RouteRecordInfo<
      '/posts/常用业务代码片段',
      '/posts/%E5%B8%B8%E7%94%A8%E4%B8%9A%E5%8A%A1%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/常用算法代码片段': RouteRecordInfo<
      '/posts/常用算法代码片段',
      '/posts/%E5%B8%B8%E7%94%A8%E7%AE%97%E6%B3%95%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/记一次从 Hexo 到 Valaxy 的迁移，及 GitHub Actions 和 Github Pages 的配合': RouteRecordInfo<
      '/posts/记一次从 Hexo 到 Valaxy 的迁移，及 GitHub Actions 和 Github Pages 的配合',
      '/posts/%E8%AE%B0%E4%B8%80%E6%AC%A1%E4%BB%8E%20Hexo%20%E5%88%B0%20Valaxy%20%E7%9A%84%E8%BF%81%E7%A7%BB%EF%BC%8C%E5%8F%8A%20GitHub%20Actions%20%E5%92%8C%20Github%20Pages%20%E7%9A%84%E9%85%8D%E5%90%88',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/（空）Google Agent Companion 白皮书阅读笔记': RouteRecordInfo<
      '/posts/（空）Google Agent Companion 白皮书阅读笔记',
      '/posts/%EF%BC%88%E7%A9%BA%EF%BC%89Google%20Agent%20Companion%20%E7%99%BD%E7%9A%AE%E4%B9%A6%E9%98%85%E8%AF%BB%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/AI Horseless Carriages': RouteRecordInfo<
      '/posts/AI Horseless Carriages',
      '/posts/AI%20Horseless%20Carriages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Cursor 实践总结': RouteRecordInfo<
      '/posts/Cursor 实践总结',
      '/posts/Cursor%20%E5%AE%9E%E8%B7%B5%E6%80%BB%E7%BB%93',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x00': RouteRecordInfo<
      '/posts/Designing Data-Intensive Applications 读书笔记 0x00',
      '/posts/Designing%20Data-Intensive%20Applications%20%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%200x00',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x01': RouteRecordInfo<
      '/posts/Designing Data-Intensive Applications 读书笔记 0x01',
      '/posts/Designing%20Data-Intensive%20Applications%20%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%200x01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x02': RouteRecordInfo<
      '/posts/Designing Data-Intensive Applications 读书笔记 0x02',
      '/posts/Designing%20Data-Intensive%20Applications%20%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%200x02',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x03': RouteRecordInfo<
      '/posts/Designing Data-Intensive Applications 读书笔记 0x03',
      '/posts/Designing%20Data-Intensive%20Applications%20%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%200x03',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x04': RouteRecordInfo<
      '/posts/Designing Data-Intensive Applications 读书笔记 0x04',
      '/posts/Designing%20Data-Intensive%20Applications%20%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%200x04',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x05': RouteRecordInfo<
      '/posts/Designing Data-Intensive Applications 读书笔记 0x05',
      '/posts/Designing%20Data-Intensive%20Applications%20%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%200x05',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/DSPy 0x01': RouteRecordInfo<
      '/posts/DSPy 0x01',
      '/posts/DSPy%200x01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Google Prompt Engineering 白皮书阅读笔记': RouteRecordInfo<
      '/posts/Google Prompt Engineering 白皮书阅读笔记',
      '/posts/Google%20Prompt%20Engineering%20%E7%99%BD%E7%9A%AE%E4%B9%A6%E9%98%85%E8%AF%BB%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-world': RouteRecordInfo<
      '/posts/hello-world',
      '/posts/hello-world',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Java 面试优质题目笔记': RouteRecordInfo<
      '/posts/Java 面试优质题目笔记',
      '/posts/Java%20%E9%9D%A2%E8%AF%95%E4%BC%98%E8%B4%A8%E9%A2%98%E7%9B%AE%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Java Lock Notes': RouteRecordInfo<
      '/posts/Java Lock Notes',
      '/posts/Java%20Lock%20Notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LeetCode-SQL-notes': RouteRecordInfo<
      '/posts/LeetCode-SQL-notes',
      '/posts/LeetCode-SQL-notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LeetCode record 2024-04': RouteRecordInfo<
      '/posts/LeetCode record 2024-04',
      '/posts/LeetCode%20record%202024-04',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LeetCode record 2024-05': RouteRecordInfo<
      '/posts/LeetCode record 2024-05',
      '/posts/LeetCode%20record%202024-05',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Oracle-Mybatis-批量更新返回值问题': RouteRecordInfo<
      '/posts/Oracle-Mybatis-批量更新返回值问题',
      '/posts/Oracle-Mybatis-%E6%89%B9%E9%87%8F%E6%9B%B4%E6%96%B0%E8%BF%94%E5%9B%9E%E5%80%BC%E9%97%AE%E9%A2%98',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Sharing Valuable Articles on AI Usage': RouteRecordInfo<
      '/posts/Sharing Valuable Articles on AI Usage',
      '/posts/Sharing%20Valuable%20Articles%20on%20AI%20Usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Stats Card': RouteRecordInfo<
      '/posts/Stats Card',
      '/posts/Stats%20Card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Windows 下 docker 使用笔记': RouteRecordInfo<
      '/posts/Windows 下 docker 使用笔记',
      '/posts/Windows%20%E4%B8%8B%20docker%20%E4%BD%BF%E7%94%A8%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.13_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser@7.29.0_@nuxt+kit@3.16.1_@types+markdown-it@14.1.2_@types+no_7ba31276614aa52fc718c7f8afbf13bc/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.13_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.13_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/关于代码规范的一些粗浅想法.md': {
      routes:
        | '/posts/关于代码规范的一些粗浅想法'
      views:
        | never
    }
    'pages/posts/分布式事务 Seata 学习笔记.md': {
      routes:
        | '/posts/分布式事务 Seata 学习笔记'
      views:
        | never
    }
    'pages/posts/北京、海、雨.md': {
      routes:
        | '/posts/北京、海、雨'
      views:
        | never
    }
    'pages/posts/常用业务代码片段.md': {
      routes:
        | '/posts/常用业务代码片段'
      views:
        | never
    }
    'pages/posts/常用算法代码片段.md': {
      routes:
        | '/posts/常用算法代码片段'
      views:
        | never
    }
    'pages/posts/记一次从 Hexo 到 Valaxy 的迁移，及 GitHub Actions 和 Github Pages 的配合.md': {
      routes:
        | '/posts/记一次从 Hexo 到 Valaxy 的迁移，及 GitHub Actions 和 Github Pages 的配合'
      views:
        | never
    }
    'pages/posts/（空）Google Agent Companion 白皮书阅读笔记.md': {
      routes:
        | '/posts/（空）Google Agent Companion 白皮书阅读笔记'
      views:
        | never
    }
    'pages/posts/AI Horseless Carriages.md': {
      routes:
        | '/posts/AI Horseless Carriages'
      views:
        | never
    }
    'pages/posts/Cursor 实践总结.md': {
      routes:
        | '/posts/Cursor 实践总结'
      views:
        | never
    }
    'pages/posts/Designing Data-Intensive Applications 读书笔记 0x00.md': {
      routes:
        | '/posts/Designing Data-Intensive Applications 读书笔记 0x00'
      views:
        | never
    }
    'pages/posts/Designing Data-Intensive Applications 读书笔记 0x01.md': {
      routes:
        | '/posts/Designing Data-Intensive Applications 读书笔记 0x01'
      views:
        | never
    }
    'pages/posts/Designing Data-Intensive Applications 读书笔记 0x02.md': {
      routes:
        | '/posts/Designing Data-Intensive Applications 读书笔记 0x02'
      views:
        | never
    }
    'pages/posts/Designing Data-Intensive Applications 读书笔记 0x03.md': {
      routes:
        | '/posts/Designing Data-Intensive Applications 读书笔记 0x03'
      views:
        | never
    }
    'pages/posts/Designing Data-Intensive Applications 读书笔记 0x04.md': {
      routes:
        | '/posts/Designing Data-Intensive Applications 读书笔记 0x04'
      views:
        | never
    }
    'pages/posts/Designing Data-Intensive Applications 读书笔记 0x05.md': {
      routes:
        | '/posts/Designing Data-Intensive Applications 读书笔记 0x05'
      views:
        | never
    }
    'pages/posts/DSPy 0x01.md': {
      routes:
        | '/posts/DSPy 0x01'
      views:
        | never
    }
    'pages/posts/Google Prompt Engineering 白皮书阅读笔记.md': {
      routes:
        | '/posts/Google Prompt Engineering 白皮书阅读笔记'
      views:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
    }
    'pages/posts/hello-world.md': {
      routes:
        | '/posts/hello-world'
      views:
        | never
    }
    'pages/posts/Java 面试优质题目笔记.md': {
      routes:
        | '/posts/Java 面试优质题目笔记'
      views:
        | never
    }
    'pages/posts/Java Lock Notes.md': {
      routes:
        | '/posts/Java Lock Notes'
      views:
        | never
    }
    'pages/posts/LeetCode-SQL-notes.md': {
      routes:
        | '/posts/LeetCode-SQL-notes'
      views:
        | never
    }
    'pages/posts/LeetCode record 2024-04.md': {
      routes:
        | '/posts/LeetCode record 2024-04'
      views:
        | never
    }
    'pages/posts/LeetCode record 2024-05.md': {
      routes:
        | '/posts/LeetCode record 2024-05'
      views:
        | never
    }
    'pages/posts/Oracle-Mybatis-批量更新返回值问题.md': {
      routes:
        | '/posts/Oracle-Mybatis-批量更新返回值问题'
      views:
        | never
    }
    'pages/posts/Sharing Valuable Articles on AI Usage.md': {
      routes:
        | '/posts/Sharing Valuable Articles on AI Usage'
      views:
        | never
    }
    'pages/posts/Stats Card.md': {
      routes:
        | '/posts/Stats Card'
      views:
        | never
    }
    'pages/posts/Windows 下 docker 使用笔记.md': {
      routes:
        | '/posts/Windows 下 docker 使用笔记'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
