/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/常见技术问题的一些不一样的看法': RouteRecordInfo<'/posts/常见技术问题的一些不一样的看法', '/posts/常见技术问题的一些不一样的看法', Record<never, never>, Record<never, never>>,
    '/posts/常用算法代码片段': RouteRecordInfo<'/posts/常用算法代码片段', '/posts/常用算法代码片段', Record<never, never>, Record<never, never>>,
    '/posts/常用业务代码片段': RouteRecordInfo<'/posts/常用业务代码片段', '/posts/常用业务代码片段', Record<never, never>, Record<never, never>>,
    '/posts/分布式事务 Seata 学习笔记': RouteRecordInfo<'/posts/分布式事务 Seata 学习笔记', '/posts/分布式事务 Seata 学习笔记', Record<never, never>, Record<never, never>>,
    '/posts/关于-Java-8-中函数式编程的粗浅见解': RouteRecordInfo<'/posts/关于-Java-8-中函数式编程的粗浅见解', '/posts/关于-Java-8-中函数式编程的粗浅见解', Record<never, never>, Record<never, never>>,
    '/posts/关于代码规范的一些粗浅想法': RouteRecordInfo<'/posts/关于代码规范的一些粗浅想法', '/posts/关于代码规范的一些粗浅想法', Record<never, never>, Record<never, never>>,
    '/posts/记一次从 Hexo 到 Valaxy 的迁移，及 GitHub Actions 和 Github Pages 的配合': RouteRecordInfo<'/posts/记一次从 Hexo 到 Valaxy 的迁移，及 GitHub Actions 和 Github Pages 的配合', '/posts/记一次从 Hexo 到 Valaxy 的迁移，及 GitHub Actions 和 Github Pages 的配合', Record<never, never>, Record<never, never>>,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x00': RouteRecordInfo<'/posts/Designing Data-Intensive Applications 读书笔记 0x00', '/posts/Designing Data-Intensive Applications 读书笔记 0x00', Record<never, never>, Record<never, never>>,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x01': RouteRecordInfo<'/posts/Designing Data-Intensive Applications 读书笔记 0x01', '/posts/Designing Data-Intensive Applications 读书笔记 0x01', Record<never, never>, Record<never, never>>,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x02': RouteRecordInfo<'/posts/Designing Data-Intensive Applications 读书笔记 0x02', '/posts/Designing Data-Intensive Applications 读书笔记 0x02', Record<never, never>, Record<never, never>>,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x03': RouteRecordInfo<'/posts/Designing Data-Intensive Applications 读书笔记 0x03', '/posts/Designing Data-Intensive Applications 读书笔记 0x03', Record<never, never>, Record<never, never>>,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x04': RouteRecordInfo<'/posts/Designing Data-Intensive Applications 读书笔记 0x04', '/posts/Designing Data-Intensive Applications 读书笔记 0x04', Record<never, never>, Record<never, never>>,
    '/posts/Designing Data-Intensive Applications 读书笔记 0x05': RouteRecordInfo<'/posts/Designing Data-Intensive Applications 读书笔记 0x05', '/posts/Designing Data-Intensive Applications 读书笔记 0x05', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/posts/Java 多线程 API 笔记': RouteRecordInfo<'/posts/Java 多线程 API 笔记', '/posts/Java 多线程 API 笔记', Record<never, never>, Record<never, never>>,
    '/posts/Java 面试优质题目笔记': RouteRecordInfo<'/posts/Java 面试优质题目笔记', '/posts/Java 面试优质题目笔记', Record<never, never>, Record<never, never>>,
    '/posts/Java Lock Notes': RouteRecordInfo<'/posts/Java Lock Notes', '/posts/Java Lock Notes', Record<never, never>, Record<never, never>>,
    '/posts/LeetCode record 2024-04': RouteRecordInfo<'/posts/LeetCode record 2024-04', '/posts/LeetCode record 2024-04', Record<never, never>, Record<never, never>>,
    '/posts/LeetCode record 2024-05': RouteRecordInfo<'/posts/LeetCode record 2024-05', '/posts/LeetCode record 2024-05', Record<never, never>, Record<never, never>>,
    '/posts/LeetCode Stats Card': RouteRecordInfo<'/posts/LeetCode Stats Card', '/posts/LeetCode Stats Card', Record<never, never>, Record<never, never>>,
    '/posts/LeetCode-SQL-notes': RouteRecordInfo<'/posts/LeetCode-SQL-notes', '/posts/LeetCode-SQL-notes', Record<never, never>, Record<never, never>>,
    '/posts/Oracle-Mybatis-批量更新返回值问题': RouteRecordInfo<'/posts/Oracle-Mybatis-批量更新返回值问题', '/posts/Oracle-Mybatis-批量更新返回值问题', Record<never, never>, Record<never, never>>,
    '/posts/Windows 下 docker 使用笔记': RouteRecordInfo<'/posts/Windows 下 docker 使用笔记', '/posts/Windows 下 docker 使用笔记', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
